# Basic Air configuration for Go projects (macOS/Linux)

root = "."
tmp_dir = "tmp"

[build]
# 1) Jalankan swag init sebelum build
#    -g sesuaikan dengan entry point kamu (mis. main.go atau cmd/server/main.go)
pre_cmd = ["swag init -g main.go -o ./docs"]

# 2) Build binary ke tmp/
cmd = "go build -o tmp/main ."
bin = "tmp/main"

# 3) Hindari watch folder hasil build & hasil swag agar tidak loop
exclude_dir = ["tmp", "vendor", "docs"]

# 4) Ekstensi yang dipantau
include_ext = ["go", "tpl", "tmpl", "html"]

# 5) File yang dikecualikan spesifik (kalau ada)
exclude_file = []

# 6) Delay kecil agar stable (ms)
delay = 1000

# 7) Stop bila build error
stop_on_error = true

# 8) Log air
log = "air.log"

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
